### ISSUE TITLE
When will the code be public ?

### ISSUE THREAD

**Issue by twotwoone221** [CRISTAL-3DSAM/Sparse2Dense-#1]
Hi Naima, 

Since two months have passed, the repository has not been updated, I wonder if there is any problem and how long it will take for the code to be public.

Looking forward to your reply.

**Comment by ForrestPi** [comment]
waitting for the code released!

**Comment by sydaoudi** [comment]
we are sorry for this delay, the code is ready but e have to clarify some  issues the licences.

**Comment by UchihaBarry** [comment]
> we are sorry for this delay, the code is ready but e have to clarify some issues the licences.
we are all waitting for the code released!

**Comment by UchihaBarry** [comment]
> we are sorry for this delay, the code is ready but e have to clarify some issues the licences.
we all badly waitting for it

**Comment by aaaaaaaaaaaly** [comment]
Today is 2022-11-26, if there is any sure date that the code will be published?

**Comment by twotwoone221** [comment]
Thank you for your sharing.

**Comment by twotwoone221** [comment]
> Today is 2022-11-26, if there is any sure date that the code will be published?

The code has been published!

**Comment by twotwoone221** [comment]
Thank you
